name: custom actions
on: 
    workflow_dispatch: 

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:

        - name: creating a file
          run: |
            echo "helllo how r u" >> 'akhil.txt'

        - name: uploding the artifact 
          uses: actions/upload-artifact@v7
          with:
            name: kumar
            path: akhil.txt

    job2:
        runs-on: ubuntu-latest
        needs: job1
        defaults:
          run:
            working-directory: pathans
        steps:
          - name: download the artifact
            uses: actions/download-artifact@v8
            with:
              name: kumar
              path: pathans
          - name: printing the file
            run: |
              cat /akhil.txt