name: test

on: 
    push: 
        branches: main

jobs:
    job1: 
        runs-on: ubuntu-latest
        outputs:
            username: ${{steps.ak.outputs.name}}
            role: ${{steps.pk.outputs.job}}

        steps:
            - name: step1
              id: ak
              run: echo "name=kumar" >> "$GITHUB_OUTPUT"

            - name: step2
              id: pk
              run: echo "job=devops" >> "$GITHUB_OUTPUT"
    
    job2: 
        runs-on: ubuntu-latest
        needs: job1

        steps:
            - name: Print outputs
              run: |
                echo "username: ${{needs.job1.outputs.username}}"
                echo "job role: ${{needs.job1.outputs.job}}"